# -*- coding: utf-8 -*-
# @Time    : 2018/7/27 下午5:18
# @Author  : Azrael.Bai
# @File    : eng_to_chinese.py

eng_list = [
    'bulletinannouncement_hz.court',
    'bulletinannouncement_hz.caseid',
    'bulletinannouncement_hz.defendants',
    'bulletinannouncement_hz.publishtime',
    'bulletinannouncement_hz.plaintiffs',
    'bulletinannouncement_hz.content',
    'bulletinannouncement_hz.type',
    'bulletinannouncement_hz.identity',
    'courtannouncement_hz.courtdate',
    'courtannouncement_hz.casecause',
    'courtannouncement_hz.judge',
    'courtannouncement_hz.plaintiffs',
    'courtannouncement_hz.publishdate',
    'courtannouncement_hz.defendants',
    'courtannouncement_hz.caseid',
    'courtannouncement_hz.court',
    'courtannouncement_hz.identity',
    'executeinfo_hz.casedate',
    'executeinfo_hz.caseid',
    'executeinfo_hz.court',
    'executeinfo_hz.object',
    'iac_hz_abnormaloperationinfo.removeoffice',
    'iac_hz_abnormaloperationinfo.removereason',
    'iac_hz_abnormaloperationinfo.enroldate',
    'iac_hz_abnormaloperationinfo.enroloffice',
    'iac_hz_abnormaloperationinfo.removedate',
    'iac_hz_abnormaloperationinfo.enrolreason',
    'iac_hz_baseinfo.mainbusiness',
    'iac_hz_baseinfo.businessscope',
    'iac_hz_baseinfo.registeredcode',
    'iac_hz_baseinfo.companytype',
    'iac_hz_baseinfo.registeredcapital',
    'iac_hz_baseinfo.address',
    'iac_hz_baseinfo.province',
    'iac_hz_baseinfo.period',
    'iac_hz_baseinfo.businessstatus',
    'iac_hz_baseinfo.registeredoffice',
    'iac_hz_baseinfo.approvaldate',
    'iac_hz_baseinfo.legalman',
    'iac_hz_baseinfo.creditcode',
    'iac_hz_baseinfo.registereddate',
    'iac_hz_baseinfo.remark',
    'iac_hz_baseinfo.realcompanyname',
    'iac_hz_baseinfo.existence',
    'iac_hz_branch.address',
    'iac_hz_branch.legalman',
    'iac_hz_branch.companyname',
    'iac_hz_branch.registeredcapital',
    'iac_hz_branch.registereddate',
    'iac_hz_changerecordsinfo.changeitem',
    'iac_hz_changerecordsinfo.aftercontent',
    'iac_hz_changerecordsinfo.changedate',
    'iac_hz_changerecordsinfo.beforecontent',
    'iac_hz_changeshareholdinginfo.changebefore',
    'iac_hz_changeshareholdinginfo.changedate',
    'iac_hz_changeshareholdinginfo.changeafter',
    'iac_hz_changeshareholdinginfo.shareholdername',
    'iac_hz_changeshareholdinginfo.publishdate',
    'iac_hz_chattelmortgageinfo.creditamount',
    'iac_hz_chattelmortgageinfo.registerednumber',
    'iac_hz_chattelmortgageinfo.registereddate',
    'iac_hz_chattelmortgageinfo.registeredoffice',
    'iac_hz_chattelmortgageinfo.publishdate',
    'iac_hz_chattelmortgageinfo.status',
    'iac_hz_equitypledgedinfo.type',
    'iac_hz_equitypledgedinfo.pledgenumber',
    'iac_hz_equitypledgedinfo.pledgeamount',
    'iac_hz_equitypledgedinfo.mortgagornumber',
    'iac_hz_equitypledgedinfo.registereddate',
    'iac_hz_equitypledgedinfo.publishdate',
    'iac_hz_equitypledgedinfo.pledgee',
    'iac_hz_equitypledgedinfo.registerednumber',
    'iac_hz_equitypledgedinfo.mortgagor',
    'iac_hz_keyperson.position',
    'iac_hz_keyperson.name',
    'iac_hz_shareholderinfo.shareholdername',
    'iac_hz_shareholderinfo.shareholdertype',
    'iac_hz_shareholderinfo.subscriptionamount',
    'iac_hz_shareholderinfo.paiedamount',
    'iac_hz_shareholderinfo.ratio',
    'judgement_hz.doccontent',
    'judgement_hz.identity',
    'judgement_hz.judgecontent',
    'judgement_hz.caseid',
    'judgement_hz.defendants',
    'judgement_hz.case_cause',
    'judgement_hz.casedate',
    'judgement_hz.casetype',
    'judgement_hz.plaintiffs',
    'judgement_hz.casename'
]

line_list = []
with open("reflect_field.txt",'r')as fs:
    for line in fs.readlines():
        line_list.append(line.strip().lower())


for item in eng_list:
    for dict_line in line_list:
        if item in dict_line:
            print item+"\t"+dict_line.split(",")[3]
            break